- name: Get dotfiles
  shell:
    - alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
    - echo ".cfg" >> .gitignore
    - git clone --bare git@gitlab.com:hmajid2301/dotfiles.git $HOME/.cfg
    - config checkout
    - dconf load / < full-backup

- name: Copy wallpaper file
  copy: src=wallpaper/ dest=/home/haseeb/pictures/wallpaper/