- name: Install Fish Shell
  roles:
    - role: dotstrap.fish

- name: Install fisher plugin manager
  shell: curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish

- name: Install fisher plugins
  shell: fisher {{ item }
  with_items:
    - jethrokuan/fzf
    - jethrokuan/z
    - jorgebucaran/bax.fish
    - jorgebucaran/nvm.fish
