- name: Install apps with apt
  apt: name={{ item }} state=present
  with_items:
    - wget
    - vim
    - tmux
    - htop
    - gtop
    - git
    - python3
    - pip
    - npm
    - node
    - bat
    - fd-find
    - fzf
    - timeshift
    - flameshot
    - code
    - gnome-tweak-tools
    - slack
