- name: Install apps with apt
  apt: name={{ item }} state=present
  with_items:
    - wget
    - vim
    - tmux
    - htop
    - gtop
    - git
    - python3
    - pip
    - fish
    - npm
    - node
    - bat
    - fd-find
    - timeshift
